/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Room_model.glb
*/

import React, { useRef, useEffect, useMemo, useState } from 'react'
import { useGLTF } from '@react-three/drei'
import * as THREE from 'three'
import { useFrame } from '@react-three/fiber'

export default function Model(props) {
  const { introDone, ...rest } = props
  const { nodes, materials } = useGLTF('/models/Room_model.glb')

  const chairTopRef = useRef()

  const linkedinGroupRef = useRef()
  const githubGroupRef = useRef()
  const gmailGroupRef = useRef()

  const [hoveredCard, setHoveredCard] = useState(null)

  const iconAnim = useRef(0)

  const linkedinPanelMaterial = useMemo(() => materials.Panels.clone(), [materials.Panels])
  const githubPanelMaterial = useMemo(() => materials.Panels.clone(), [materials.Panels])
  const gmailPanelMaterial = useMemo(() => materials.Panels.clone(), [materials.Panels])

  const linkedinIconMaterial = useMemo(() => materials.Linkedin.clone(), [materials.Linkedin])
  const githubIconMaterial = useMemo(() => materials.Github.clone(), [materials.Github])
  const gmailIconMaterial = useMemo(() => materials.Gmail.clone(), [materials.Gmail])

  useEffect(() => {
    document.body.style.cursor = hoveredCard ? 'pointer' : 'default'
    return () => {
      document.body.style.cursor = 'default'
    }
  }, [hoveredCard])

  useFrame((state) => {
    const t = state.clock.getElapsedTime()

    if (chairTopRef.current) {
      chairTopRef.current.rotation.y = Math.sin(t * 0.8) * 0.1
    }
  })

  const getPivotFromGeometries = (...geometries) => {
    const tempBox = new THREE.Box3()
    const unionBox = new THREE.Box3()

    geometries.forEach((geometry, index) => {
      if (!geometry.boundingBox) geometry.computeBoundingBox()
      tempBox.copy(geometry.boundingBox)

      if (index === 0) {
        unionBox.copy(tempBox)
      } else {
        unionBox.union(tempBox)
      }
    })

    const center = new THREE.Vector3()
    unionBox.getCenter(center)
    return center
  }

  const linkedinPivot = useMemo(() => {
    return getPivotFromGeometries(nodes.Cube035.geometry, nodes.Cube035_1.geometry)
  }, [nodes])

  const githubPivot = useMemo(() => {
    return getPivotFromGeometries(nodes.Cube036.geometry, nodes.Cube036_1.geometry)
  }, [nodes])

  const gmailPivot = useMemo(() => {
    return getPivotFromGeometries(nodes.Curve009.geometry, nodes.Curve009_1.geometry)
  }, [nodes])

  const linkedinBasePos = useMemo(
    () => new THREE.Vector3(linkedinPivot.x, linkedinPivot.y, linkedinPivot.z),
    [linkedinPivot]
  )

  const githubBasePos = useMemo(
    () => new THREE.Vector3(githubPivot.x, githubPivot.y, githubPivot.z),
    [githubPivot]
  )

  const gmailBasePos = useMemo(
    () => new THREE.Vector3(gmailPivot.x, gmailPivot.y, gmailPivot.z),
    [gmailPivot]
  )

  const setMaterialOpacity = (material, opacity) => {
    if (!material) return
    material.transparent = true
    material.opacity = opacity
  }

  useEffect(() => {
    iconAnim.current = 0

    const resetGroup = (group, basePos, mats) => {
      if (!group.current) return

      group.current.position.copy(basePos)
      group.current.position.y += 0.16
      group.current.scale.setScalar(0.96)
      group.current.rotation.z = -0.08

      mats.forEach((mat) => setMaterialOpacity(mat, 0))
    }

    resetGroup(linkedinGroupRef, linkedinBasePos, [
      linkedinPanelMaterial,
      linkedinIconMaterial,
    ])

    resetGroup(githubGroupRef, githubBasePos, [
      githubPanelMaterial,
      githubIconMaterial,
    ])

    resetGroup(gmailGroupRef, gmailBasePos, [
      gmailIconMaterial,
      gmailPanelMaterial,
    ])
  }, [
    introDone,
    linkedinBasePos,
    githubBasePos,
    gmailBasePos,
    linkedinPanelMaterial,
    linkedinIconMaterial,
    githubPanelMaterial,
    githubIconMaterial,
    gmailIconMaterial,
    gmailPanelMaterial,
  ])

  useFrame((_, delta) => {
    if (!introDone) return

    iconAnim.current = Math.min(iconAnim.current + delta * 1.35, 1)

    const easeOutBounce = (x) => {
      const n1 = 7.5625
      const d1 = 2.75

      if (x < 1 / d1) {
        return n1 * x * x
      } else if (x < 2 / d1) {
        return n1 * (x -= 1.5 / d1) * x + 0.75
      } else if (x < 2.5 / d1) {
        return n1 * (x -= 2.25 / d1) * x + 0.9375
      } else {
        return n1 * (x -= 2.625 / d1) * x + 0.984375
      }
    }

    const easeOutCubic = (x) => 1 - Math.pow(1 - x, 3)

    const animateIntroGroup = (group, delay, basePos, mats) => {
      if (!group.current) return

      const raw = Math.max(0, Math.min(1, (iconAnim.current - delay) / 0.42))
      const bounceT = easeOutBounce(raw)
      const fadeT = easeOutCubic(raw)

      group.current.position.set(
        basePos.x,
        basePos.y + (1 - bounceT) * 0.16,
        basePos.z
      )

      group.current.rotation.z = -0.08 * (1 - fadeT)

      const scale = 0.96 + (1 - 0.96) * fadeT
      group.current.scale.setScalar(scale)

      mats.forEach((mat) => setMaterialOpacity(mat, fadeT))
    }

    

    animateIntroGroup(githubGroupRef, 0.00, githubBasePos, [
      githubPanelMaterial,
      githubIconMaterial,
    ])
    animateIntroGroup(linkedinGroupRef, 0.15, linkedinBasePos, [
      linkedinPanelMaterial,
      linkedinIconMaterial,
    ])

    animateIntroGroup(gmailGroupRef, 0.30, gmailBasePos, [
      gmailIconMaterial,
      gmailPanelMaterial,
    ])

    const applyHoverLift = (group, basePos, isHovered) => {
      if (!group.current) return

      const targetY = basePos.y + (isHovered ? 0.3 : 0)
      group.current.position.y = THREE.MathUtils.lerp(
        group.current.position.y,
        targetY,
        0.12
      )
    }

    applyHoverLift(linkedinGroupRef, linkedinBasePos, hoveredCard === 'linkedin')
    applyHoverLift(githubGroupRef, githubBasePos, hoveredCard === 'github')
    applyHoverLift(gmailGroupRef, gmailBasePos, hoveredCard === 'gmail')
  })

  const openExternal = (url) => {
    window.open(url, '_blank', 'noopener,noreferrer')
  }

  const openEmail = () => {
    window.location.href = 'mailto:hapitino@gmail.com'
  }

  return (
    <group {...rest} dispose={null}>
      <mesh geometry={nodes.Skyline.geometry} material={materials.Skyline} />

      <mesh geometry={nodes.BackgroundBox.geometry}>
        <meshStandardMaterial
          color="#000000"
          roughness={0.9}
          metalness={0}
          toneMapped={false}
        />
      </mesh>

      <mesh geometry={nodes.Cat_Led.geometry} material={materials.CatLED} />
      <mesh geometry={nodes.Linkedin_light.geometry} material={materials['Emissive 3500.010']} />
      <mesh geometry={nodes.Lighting.geometry} material={materials['Emission Light']} />

      <mesh geometry={nodes.Window.geometry}>
        <meshPhysicalMaterial
          transmission={1}
          roughness={0}
          thickness={0.1}
          ior={1.3}
          transparent
          opacity={1}
          envMapIntensity={0.4}
        />
      </mesh>

      <mesh geometry={nodes.Curtains.geometry}>
        <meshStandardMaterial
          color="#435586"
          transparent
          opacity={0.7}
          roughness={0.9}
          metalness={0}
          side={THREE.DoubleSide}
        />
      </mesh>

      <mesh geometry={nodes.TextureSetOne.geometry} material={materials.TextureSetOne} />
      <mesh geometry={nodes.TextureSetTwo.geometry} material={materials.TextureSetTwo} />
      <mesh geometry={nodes.Circle.geometry} material={materials['Material.005']} />
      <mesh geometry={nodes.Circle_1.geometry} material={materials.screen} />

      <mesh
        ref={chairTopRef}
        geometry={nodes.ChairTop.geometry}
        position={[0.643, 0.509, -0.438]}
        material={materials.TextureSetTwo}
      />

      <mesh geometry={nodes.Circle_2.geometry} material={materials['Material.006']} />
      <mesh geometry={nodes.Circle_3.geometry} material={materials['Material.009']} />

      {/* LinkedIn */}
      <group
        ref={linkedinGroupRef}
        position={[linkedinPivot.x, linkedinPivot.y, linkedinPivot.z]}
        onPointerOver={(e) => {
          e.stopPropagation()
          setHoveredCard('linkedin')
        }}
        onPointerOut={() => setHoveredCard(null)}
        onClick={(e) => {
          e.stopPropagation()
          openExternal('https://www.linkedin.com/in/hanna-pitino/')
        }}
      >
        <mesh
          geometry={nodes.Cube035.geometry}
          material={linkedinPanelMaterial}
          position={[-linkedinPivot.x, -linkedinPivot.y, -linkedinPivot.z]}
        />
        <mesh
          geometry={nodes.Cube035_1.geometry}
          material={linkedinIconMaterial}
          position={[-linkedinPivot.x, -linkedinPivot.y, -linkedinPivot.z]}
        />
      </group>

      {/* GitHub */}
      <group
        ref={githubGroupRef}
        position={[githubPivot.x, githubPivot.y, githubPivot.z]}
        onPointerOver={(e) => {
          e.stopPropagation()
          setHoveredCard('github')
        }}
        onPointerOut={() => setHoveredCard(null)}
        onClick={(e) => {
          e.stopPropagation()
          openExternal('https://github.com/hpitino11')
        }}
      >
        <mesh
          geometry={nodes.Cube036.geometry}
          material={githubPanelMaterial}
          position={[-githubPivot.x, -githubPivot.y, -githubPivot.z]}
        />
        <mesh
          geometry={nodes.Cube036_1.geometry}
          material={githubIconMaterial}
          position={[-githubPivot.x, -githubPivot.y, -githubPivot.z]}
        />
      </group>

      {/* Gmail */}
      <group
        ref={gmailGroupRef}
        position={[gmailPivot.x, gmailPivot.y, gmailPivot.z]}
        onPointerOver={(e) => {
          e.stopPropagation()
          setHoveredCard('gmail')
        }}
        onPointerOut={() => setHoveredCard(null)}
        onClick={(e) => {
          e.stopPropagation()
          openEmail()
        }}
      >
        <mesh
          geometry={nodes.Curve009.geometry}
          material={gmailIconMaterial}
          position={[-gmailPivot.x, -gmailPivot.y, -gmailPivot.z]}
        />
        <mesh
          geometry={nodes.Curve009_1.geometry}
          material={gmailPanelMaterial}
          position={[-gmailPivot.x, -gmailPivot.y, -gmailPivot.z]}
        />
      </group>

      <mesh geometry={nodes.Cube017.geometry} material={materials['Emissive 3500']} />
      <mesh geometry={nodes.Cube017_1.geometry} material={materials['Emission Light.002']} />
    </group>
  )
}

useGLTF.preload('/models/Room_model.glb')